name: Deploy Angular Project to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'  # Use the node version specified in your project

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --prod --output-path=dist/angular-practices  # Update with your project's output path

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-app  # Update with your build output directory
